name: testflow
on:
  push:
    branches:
      - 'c368team03'
jobs:
  test-build-again:
    name: Test Build Two
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Print Directory
        run: echo ${{ github.workspace }}

      - name: Build and Publish Front End
        id: build-img-fe
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: "ecrlist-ps"
          IMAGE_TAG: latest
          BRANCH: 'c368team03'
          TAG: "c368team03fe-dev-test"
        run: |
          echo "Testing building here."
          echo "${{github.workspace}}/Dockerfiles/Dockerfile_nginx"
          echo "$TAG"
          docker build -f ${{github.workspace}}/Dockerfiles/Dockerfile_nginx -t $ECR_REGISTRY/$ECR_REPOSITORY:$TAG .
          echo "We got here!"
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$TAG
